# Site settings
title: Clean Blog

# Default header image
header_img:
  url: "assets/img/home-bg.jpg"

comments:
  enabled: true
  disqus_shortname: yosymfony

social_networks:
    twitter: spress_cms # Your id without @
    facebook:  # Your URL
    instagram: # Your id
    github: https://github.com/spress/Spress
    dribbble: # Your id
    linkedin: # Your URL
    email: # Your email adress you@yoourDomain.com

# Forms
forms:
    contact:
        getsimpleform_api_token:
