# Site settings
title: Clean Blog

# Default header image
header_img:
  url: "img/home-bg.jpg"

comments:
  enabled: true
  disqus_shortname: yosymfony

social_networks:
    twitter: spress_cms # Your id without @
    facebook:  # Your URL
    instagram: # Your id
    github: https://github.com/spress/Spress
    dribbble: # Your id
    linkedin: # Your URL
    email: # Your email adress you@yoourDomain.com

# Forms
forms:
    contact:
        action_url: "#"  # Your Getsimple form URL http://getsimpleform.com/messages/ajax?form_api_token=

# Build settings
paginate: 5

exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md

